# ===========================
# Server
# ===========================
server.port=${PORT:8081}

# ===========================
# Database - PostgreSQL (Render)
# ===========================
spring.datasource.url=jdbc:postgresql://dpg-d75lkebuibrs73bq0ae0-a.singapore-postgres.render.com:5432/jobapplicationportal_db
spring.datasource.username=jobapplicationportal_db_user
spring.datasource.password=m5kJ6BPjE492wgpngmMjVUyCHBRJ6Z3k
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# JWT
# ===========================
app.jwt.secret=YourSuperSecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmSecurity
app.jwt.expiration=86400000

# ===========================
# Logging
# ===========================
logging.level.com.jobportal=DEBUG
logging.level.org.springframework.security=DEBUG

# ===========================
# Other
# ===========================
spring.jpa.open-in-view=false